export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS";

export const GET_GENERAL_DATA = "GET_GENERAL_DATA";
export const GET_GENERAL_DATA_SUCCESS = "GET_GENERAL_DATA_SUCCESS";

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const MOST_VIEW = "MOST_VIEW";
export const MOST_VIEW_SUCCESS = "MOST_VIEW_SUCCESS";

export const HEADER_TITLE = "HEADER_TITLE";


export const POST_INFORMATION_DELIVERY_USER = "POST_INFORMATION_DELIVERY_USER";
export const POST_INFORMATION_DELIVERY_USER_SUCCESS = "POST_INFORMATION_DELIVERY_USER_SUCCESS";

export const GET_INFORMATION_DELIVERY_USER = "GET_INFORMATION_DELIVERY_USER";
export const GET_INFORMATION_DELIVERY_USER_SUCCESS = "GET_INFORMATION_DELIVERY_USER_SUCCESS";

export const TARGET_ONE_INFORMATION_DELIVERY_USER = "TARGET_ONE_INFORMATION_DELIVERY_USER";

export const PUT_INFORMATION_DELIVERY_USER = "PUT_INFORMATION_DELIVERY_USER";
export const PUT_INFORMATION_DELIVERY_USER_SUCCESS = "PUT_INFORMATION_DELIVERY_USER_SUCCESS";