export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS";

export const GET_GENERAL_DATA = "GET_GENERAL_DATA";
export const GET_GENERAL_DATA_SUCCESS = "GET_GENERAL_DATA_SUCCESS";

export const GET_REGISTERED_CUSTOMER = "GET_REGISTERED_CUSTOMER";
export const GET_REGISTERED_CUSTOMER_SUCCESS = "GET_REGISTERED_CUSTOMER_SUCCESS";

export const REGISTER_CUSTOMER = "REGISTER_CUSTOMER";
export const REGISTER_CUSTOMER_SUCCESS = "REGISTER_CUSTOMER_SUCCESS";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";

export const SET_ACTIVE_TYPE = "SET_ACTIVE_TYPE";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const UPDATE_CART = "UPDATE_CART";

export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY";
export const GET_LIST_CATEGORY_SUCCESS = "GET_LIST_CATEGORY_SUCCESS";

export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS";

export const GET_LIST_ORDER = "GET_LIST_ORDER";
export const GET_LIST_ORDER_SUCCESS = "GET_LIST_ORDER_SUCCESS";

export const GET_ONE_ORDER = "GET_ONE_ORDER";
export const GET_ONE_ORDER_SUCCESS = "GET_ONE_ORDER_SUCCESS";

export const SUBMIT_ORDER = "SUBMIT_ORDER";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";

export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";

export const GET_LIST_VOUCHER = "GET_LIST_VOUCHER";
export const GET_LIST_VOUCHER_SUCCESS = "GET_LIST_VOUCHER_SUCCESS";

export const USE_VOUCHER = "USE_VOUCHER";
export const USE_VOUCHER_SUCCESS = "USE_VOUCHER_SUCCESS";

export const GET_VERIFY_TOKEN = "GET_VERIFY_TOKEN";
export const GET_VERIFY_TOKEN_SUCCESS = "GET_VERIFY_TOKEN_SUCCESS";

export const VERIFY_CUSTOMER = "VERIFY_CUSTOMER";
export const VERIFY_CUSTOMER_SUCCESS = "VERIFY_CUSTOMER_SUCCESS";
